name: Push CocoaPod on Tag

on:
  push:
    tags:
      - '*'

  # Manual trigger
  workflow_dispatch:

jobs:
  push_pod:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Make sure this version matches your project's Ruby version

    - name: Install CocoaPods
      run: gem install cocoapods

    - name: Run Unit Tests with xcodebuild
      run: |
          xcodebuild test \
            -project ./ORLib/ORLib.xcodeproj \
            -scheme Tests \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'

    - name: Validate Podspec
      run: pod lib lint ./ORLib/ORLib.podspec --skip-tests

    - name: Push to CocoaPods Trunk
      run: pod trunk push ./ORLib/ORLib.podspec --allow-warnings --skip-tests
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
