name: Push CocoaPod on Tag

on:
  push:
    tags:
      - '*'

jobs:
  push_pod:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Make sure this version matches your project's Ruby version

    - name: Install CocoaPods
      run: gem install cocoapods

    - name: Validate Podspec
      run: pod lib lint

    - name: Push to CocoaPods Trunk
      run: pod trunk push ORLib.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
